In [2]:
import numpy as np

In [2]:
np.__version__

'2.3.4'

## Create & Read

### 1D Array

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

In [9]:
arr1.size

5

### 2D Array

In [11]:
arr2 = np.array([[1,4,5],[6,7,8]])
arr2

array([[1, 4, 5],
       [6, 7, 8]])

In [12]:
arr2.ndim

2

In [14]:
arr2.shape # (row,column)

(2, 3)

In [15]:
arr2.dtype

dtype('int64')

In [16]:
arr2.size

6

### 3D Array

In [20]:
arr3 = np.array([[[1,4,5],[6,7,8]], [[3,5,4],[5,8,7]], [[1,4,5],[6,7,8]]])
arr3

array([[[1, 4, 5],
        [6, 7, 8]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 8]]])

In [21]:
arr3.ndim

3

In [24]:
arr3.shape  #(number of outside layer or the number or 2D arrays, no. of 1D arrays in a 2D array, number of values in a 1D array)

(3, 2, 3)

In [25]:
arr3.size

18

### Create Random Array

In [26]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.42133218, 0.37750597, 0.69794692],
        [0.06312742, 0.95057005, 0.6429484 ]],

       [[0.03183152, 0.0314045 , 0.55495314],
        [0.58223406, 0.16701681, 0.46967876]],

       [[0.00887843, 0.71649233, 0.55180618],
        [0.5177515 , 0.46581456, 0.4547492 ]]])

In [27]:
randomArr.dtype

dtype('float64')

In [29]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
zeroes.ndim

3

In [31]:
full = np.full((3,2,3) ,8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [33]:
ones = np.ones((3,2,3))

In [34]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 8]])

In [35]:
arr3[0][0]

array([1, 4, 5])

In [36]:
arr3[0][0][1]

np.int64(4)

In [37]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 8]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [38]:
arr3[-3]

array([[1, 4, 5],
       [6, 7, 8]])

In [40]:
arr3[1][0][1] # Or arr3[1, 0, 1]

np.int64(5)

### Update & Delete

In [41]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [42]:
a1

array([[[0.86378475, 0.52420621],
        [0.02736516, 0.54209217],
        [0.95428256, 0.69328914]],

       [[0.68315378, 0.11914963],
        [0.44217666, 0.25357697],
        [0.4273651 , 0.76381832]]])

In [43]:
a2

array([[[0.56122819, 0.01063885],
        [0.17028145, 0.30866405],
        [0.97371011, 0.44054962]],

       [[0.01520189, 0.19815914],
        [0.01062829, 0.82300583],
        [0.93673265, 0.79930766]]])

#### Basic Math Operations

In [44]:
np.add(a1, a2)

array([[[1.42501294, 0.53484506],
        [0.19764662, 0.85075622],
        [1.92799267, 1.13383876]],

       [[0.69835566, 0.31730877],
        [0.45280495, 1.07658281],
        [1.36409775, 1.56312598]]])

In [45]:
np.subtract(a1, a2)

array([[[ 0.30255656,  0.51356736],
        [-0.14291629,  0.23342812],
        [-0.01942755,  0.25273951]],

       [[ 0.66795189, -0.07900951],
        [ 0.43154837, -0.56942886],
        [-0.50936754, -0.03548934]]])

In [46]:
np.divide(a1,a2)

array([[[ 1.53909722, 49.27282824],
        [ 0.16070548,  1.75625303],
        [ 0.98004791,  1.57369135]],

       [[44.93874584,  0.60128256],
        [41.60373231,  0.30811078],
        [ 0.45622954,  0.9555999 ]]])

In [47]:
np.multiply(a1,a2)

array([[[0.48478036, 0.00557695],
        [0.00465978, 0.16732437],
        [0.92919457, 0.30542827]],

       [[0.01038523, 0.02361059],
        [0.00469958, 0.20869533],
        [0.40032684, 0.61052583]]])

#### Satistical Operations

In [48]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [49]:
sqrt

np.float64(5.0)

In [50]:
abs

np.int64(2)

In [51]:
power

np.int64(256)

In [52]:
log

np.float64(3.2188758248682006)

In [53]:
mins

np.float64(0.027365163322362163)

In [54]:
maxs

np.float64(0.9737101108143775)

#### Update

In [55]:
arr3

array([[[1, 4, 5],
        [6, 7, 8]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 8]]])

In [56]:
arr3[0,0,2] = 6
arr3

array([[[1, 4, 6],
        [6, 7, 8]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 8]]])

In [57]:
arr3.sort()
arr3

array([[[1, 4, 6],
        [6, 7, 8]],

       [[3, 4, 5],
        [5, 7, 8]],

       [[1, 4, 5],
        [6, 7, 8]]])

In [58]:
# Reshape
arr3.shape

(3, 2, 3)

In [59]:
arr3_new = arr3.reshape((2,3,3))
arr3_new

array([[[1, 4, 6],
        [6, 7, 8],
        [3, 4, 5]],

       [[5, 7, 8],
        [1, 4, 5],
        [6, 7, 8]]])

#### Appending and Inserting

In [60]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [64]:
new_arrays = np.ones((3,2,3))
new_arrays

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [66]:
appd = np.append(zeroes, new_arrays, axis=0) # axis 0 = rows, axis 1 = columns
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [67]:
# Insert 
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [68]:
new_arrays

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [69]:
inserted_array = np.insert(zeroes, 1, new_arrays, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### Delete

In [3]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.88385337, 0.70912283, 0.64666112],
        [0.75737015, 0.71667477, 0.50007723]],

       [[0.85928537, 0.98443991, 0.95568737],
        [0.44043003, 0.23049335, 0.05422226]],

       [[0.80015618, 0.25090026, 0.28430119],
        [0.20814266, 0.83597134, 0.87031557]]])

In [5]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.75737015, 0.71667477, 0.50007723]],

       [[0.44043003, 0.23049335, 0.05422226]],

       [[0.20814266, 0.83597134, 0.87031557]]])

In [6]:
np.save("new_array", arr5)

In [7]:
np.load("new_array.npy")

array([[[0.75737015, 0.71667477, 0.50007723]],

       [[0.44043003, 0.23049335, 0.05422226]],

       [[0.20814266, 0.83597134, 0.87031557]]])